# Generated by Django 3.0.5 on 2020-04-23 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='asset',
            name='baseprice',
            field=models.DecimalField(decimal_places=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='auctionedasset',
            name='asset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bidding.Asset'),
        ),
        migrations.AlterField(
            model_name='auctionedasset',
            name='auction_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bidding.Auction'),
        ),
        migrations.AlterField(
            model_name='auctionedasset',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bidding.Buyer'),
        ),
        migrations.AlterField(
            model_name='auctionedasset',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='auctionedasset',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bidding.Seller'),
        ),
        migrations.CreateModel(
            name='LiveAuction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=0, max_digits=9)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bidding.Asset')),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bidding.Buyer')),
            ],
        ),
    ]
