# Generated by Django 3.0.2 on 2020-02-05 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0002_auto_20200205_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuctionedAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('ac_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bidding.Auction')),
                ('b_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bidding.Buyer')),
                ('s_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bidding.Seller')),
            ],
        ),
    ]
