# Generated by Django 3.0.2 on 2020-02-15 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0003_auctionedasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionedasset',
            name='category',
            field=models.CharField(choices=[('CAR', 'CAR'), ('HOUSE', 'HOUSE')], default=None, max_length=5),
        ),
    ]
