# Generated by Django 3.0.2 on 2020-02-05 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0003_auction_auctionedasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='sellerid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bidding.Seller'),
        ),
        migrations.AddField(
            model_name='buyer',
            name='contact',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='seller',
            name='contact',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
