# Generated by Django 3.0.2 on 2020-02-15 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0004_auctionedasset_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionedasset',
            name='category',
            field=models.CharField(choices=[('CAR', 'CAR'), ('HOUSE', 'HOUSE')], default=None, max_length=5, null=True),
        ),
    ]
