# Generated by Django 3.0.2 on 2020-02-05 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0004_auto_20200205_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='sellerid',
            new_name='seller',
        ),
    ]
