# Generated by Django 3.0.2 on 2020-02-06 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0005_auto_20200205_1724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='img',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='auctionedasset',
            old_name='ac_id',
            new_name='auction_id',
        ),
        migrations.RenameField(
            model_name='auctionedasset',
            old_name='b_id',
            new_name='buyer',
        ),
        migrations.RenameField(
            model_name='auctionedasset',
            old_name='s_id',
            new_name='seller',
        ),
    ]
