# Generated by Django 3.0.2 on 2020-02-15 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0005_auto_20200216_0247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionedasset',
            name='category',
        ),
    ]
