# Generated by Django 3.0.2 on 2020-02-15 17:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0007_auctionedasset_asset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='id',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='id',
        ),
        migrations.AddField(
            model_name='auction',
            name='category',
            field=models.CharField(choices=[('CAR', 'CAR'), ('HOUSE', 'HOUSE')], default=django.utils.timezone.now, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buyer',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='seller',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
