# Generated by Django 3.0.2 on 2020-02-15 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuctionedAsset',
        ),
    ]
