# Generated by Django 3.0.2 on 2020-02-15 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0002_delete_auctionedasset'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionedAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bidding.Asset')),
                ('auction_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bidding.Auction')),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bidding.Buyer')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bidding.Seller')),
            ],
        ),
    ]
