# Generated by Django 3.0.2 on 2020-02-06 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0006_auto_20200206_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionedasset',
            name='asset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bidding.Asset'),
        ),
    ]
